name: couchbase
version: 0.0.2
description: >
  Couchbase C SDK x Dart Native Extension
author: Benjamin Thong <BenjaminThong@gmail.com>
homepage: https://github.com/BenjaminThong/couchbase.dart
environment:
    sdk: ">=1.8.0 <2.0.0"
dependencies:
  test: ^0.12.28
